<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=10)),
                ('job_location', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=4000)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('Date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Done')])),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
            options={
                'verbose_name_plural': 'applications',
                'db_table': 'applications',
                'managed': True,
            },
        ),
    ]
=======
# Generated by Django 4.2.1 on 2023-05-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
                ('job_type', models.CharField(max_length=10)),
                ('job_location', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=4000)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('Date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Done')])),
                ('applicant_id', models.IntegerField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
            options={
                'verbose_name_plural': 'applications',
                'db_table': 'applications',
                'managed': True,
            },
        ),
    ]
>>>>>>> 19f35fee6084b7de9e3e5327b4da6abed7b40676
