# Generated by Django 4.2.1 on 2023-05-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('job_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')])),
                ('job_location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=4000)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('Date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employer')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Done')])),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.TextField(max_length=4000)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('estimated_salary', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'managed': True,
            },
        ),
    ]
